// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.887
package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "blog/internals/templates/layouts"

func HomePage() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"bg-red-200\"><div class=\"container mx-auto px-4 py-8\"><main class=\"max-w-4xl mx-auto\"><div class=\"grid md:grid-cols-2 lg:grid-cols-3 gap-6\"><article class=\"bg-white rounded-lg shadow-md hover:shadow-lg transition-shadow duration-300 p-6\"><h2 class=\"text-xl font-semibold text-gray-800 mb-3\">Первая статья</h2><p class=\"text-gray-600 mb-4\">Краткое описание первой статьи в блоге.</p><a href=\"#\" class=\"text-blue-600 hover:text-blue-800 font-medium\">Читать далее →</a></article><article class=\"bg-white rounded-lg shadow-md hover:shadow-lg transition-shadow duration-300 p-6\"><h2 class=\"text-xl font-semibold text-gray-800 mb-3\">Вторая статья</h2><p class=\"text-gray-600 mb-4\">Краткое описание второй статьи в блоге.</p><a href=\"#\" class=\"text-blue-600 hover:text-blue-800 font-medium\">Читать далее →</a></article><article class=\"bg-white rounded-lg shadow-md hover:shadow-lg transition-shadow duration-300 p-6\"><h2 class=\"text-xl font-semibold text-gray-800 mb-3\">Третья статья</h2><p class=\"text-gray-600 mb-4\">Краткое описание третьей статьи в блоге.</p><a href=\"#\" class=\"text-blue-600 hover:text-blue-800 font-medium\">Читать далее →</a></article></div></main></div></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = layouts.AppLayout("Главная страница!!", "ru").Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
